"""many to many relationship added

Revision ID: 44c15d09671a
Revises: d8e56a8d1d75
Create Date: 2020-12-26 13:27:19.555967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c15d09671a'
down_revision = 'd8e56a8d1d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_book',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    op.drop_table('user_book')
    # ### end Alembic commands ###
