"""empty message

Revision ID: 52c3c99cc17b
Revises: 909cc758409b
Create Date: 2020-11-14 14:30:37.873170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c3c99cc17b'
down_revision = '909cc758409b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book', ['name'])
    op.drop_column('book', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'book', type_='unique')
    # ### end Alembic commands ###
