"""empty message

Revision ID: 6920a52d0314
Revises: 943e9b5709b8
Create Date: 2020-11-10 16:14:53.265544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6920a52d0314'
down_revision = '943e9b5709b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image', flask_appbuilder.models.mixins.ImageColumn(), nullable=True))
    op.create_unique_constraint(None, 'book', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_column('book', 'image')
    # ### end Alembic commands ###
