"""empty message

Revision ID: 909cc758409b
Revises: b3f3c116063d
Create Date: 2020-11-14 12:47:06.719482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909cc758409b'
down_revision = 'b3f3c116063d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image_name', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'book', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_column('book', 'image_name')
    # ### end Alembic commands ###
