"""empty message

Revision ID: a41e188f8517
Revises: 6920a52d0314
Create Date: 2020-11-10 16:19:25.607370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41e188f8517'
down_revision = '6920a52d0314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    # ### end Alembic commands ###
