"""empty message

Revision ID: b2c448463ea7
Revises: 43250d906e14
Create Date: 2020-12-25 19:41:14.156373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c448463ea7'
down_revision = '43250d906e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_public')
    # ### end Alembic commands ###
