"""empty message

Revision ID: b2d2a6b2421e
Revises: 44c15d09671a
Create Date: 2020-12-26 14:17:38.898640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d2a6b2421e'
down_revision = '44c15d09671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
