"""empty message

Revision ID: b3f3c116063d
Revises: 1759e302483b
Create Date: 2020-11-13 22:09:40.451499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f3c116063d'
down_revision = '1759e302483b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    # ### end Alembic commands ###
