"""removed images

Revision ID: f32c9d2ebac0
Revises: 1a1ce13d803c
Create Date: 2020-11-17 19:29:41.130625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32c9d2ebac0'
down_revision = '1a1ce13d803c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'image_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image_name', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
